Traceback (most recent call last):
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jaloef/anaconda3/envs/infovis/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Create a layout object that contains the specifications for the X and Y axes.
layout = go.Layout(
    title = "Bipolar disorder (%), Happiness and GDP per region",
    xaxis=go.layout.XAxis(
        type='category'
    ),
    xaxis_title="Regional Indicator",
    yaxis_title="Strength",
)

    
trace1 = go.Bar (
    x = df_mean["Regional Indicator"],
    y = df_mean["Bipolar disorder (%)"],
    name = "Bipolar disorder (%)",
    marker = dict(
        color = 'rgb(252, 115, 3)'
    )
)

trace2 = go.Bar (
    x = df_mean["Regional Indicator"],
    y = df_mean["Life Ladder"],
    name = "Happiness",
    marker = dict(
        color = 'rgb(14, 174, 237)'
    )
)

trace3 = go.Bar (
    x = df_mean["Regional Indicator"],
    y = df_mean["Log GDP Per Capita"],
    name = "GDP",
    marker = dict(
        color = 'rgb(135, 18, 219)'
    )
)

# Create a list of the traces.
data = [trace1, trace2, trace3]

# Create a figure object with the data and layout objects.
fig = go.Figure(data=data, layout=layout)

# Show the figure.
fig.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/anaconda3/envs/infovis/lib/python3.11/site-packages/pandas/core/indexes/base.py:3652[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3651[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3652[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3653[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/envs/infovis/lib/python3.11/site-packages/pandas/_libs/index.pyx:147[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32m~/anaconda3/envs/infovis/lib/python3.11/site-packages/pandas/_libs/index.pyx:176[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7080[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7088[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'Bipolar disorder (%)'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[5], line 14[0m
[1;32m      1[0m [38;5;66;03m# Create a layout object that contains the specifications for the X and Y axes.[39;00m
[1;32m      2[0m layout [38;5;241m=[39m go[38;5;241m.[39mLayout(
[1;32m      3[0m     title [38;5;241m=[39m [38;5;124m"[39m[38;5;124mBipolar disorder ([39m[38;5;124m%[39m[38;5;124m), Happiness and GDP per region[39m[38;5;124m"[39m,
[1;32m      4[0m     xaxis[38;5;241m=[39mgo[38;5;241m.[39mlayout[38;5;241m.[39mXAxis(
[0;32m   (...)[0m
[1;32m      8[0m     yaxis_title[38;5;241m=[39m[38;5;124m"[39m[38;5;124mStrength[39m[38;5;124m"[39m,
[1;32m      9[0m )
[1;32m     12[0m trace1 [38;5;241m=[39m go[38;5;241m.[39mBar (
[1;32m     13[0m     x [38;5;241m=[39m df_mean[[38;5;124m"[39m[38;5;124mRegional Indicator[39m[38;5;124m"[39m],
[0;32m---> 14[0m     y [38;5;241m=[39m [43mdf_mean[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mBipolar disorder ([39;49m[38;5;124;43m%[39;49m[38;5;124;43m)[39;49m[38;5;124;43m"[39;49m[43m][49m,
[1;32m     15[0m     name [38;5;241m=[39m [38;5;124m"[39m[38;5;124mBipolar disorder ([39m[38;5;124m%[39m[38;5;124m)[39m[38;5;124m"[39m,
[1;32m     16[0m     marker [38;5;241m=[39m [38;5;28mdict[39m(
[1;32m     17[0m         color [38;5;241m=[39m [38;5;124m'[39m[38;5;124mrgb(252, 115, 3)[39m[38;5;124m'[39m
[1;32m     18[0m     )
[1;32m     19[0m )
[1;32m     21[0m trace2 [38;5;241m=[39m go[38;5;241m.[39mBar (
[1;32m     22[0m     x [38;5;241m=[39m df_mean[[38;5;124m"[39m[38;5;124mRegional Indicator[39m[38;5;124m"[39m],
[1;32m     23[0m     y [38;5;241m=[39m df_mean[[38;5;124m"[39m[38;5;124mLife Ladder[39m[38;5;124m"[39m],
[0;32m   (...)[0m
[1;32m     27[0m     )
[1;32m     28[0m )
[1;32m     30[0m trace3 [38;5;241m=[39m go[38;5;241m.[39mBar (
[1;32m     31[0m     x [38;5;241m=[39m df_mean[[38;5;124m"[39m[38;5;124mRegional Indicator[39m[38;5;124m"[39m],
[1;32m     32[0m     y [38;5;241m=[39m df_mean[[38;5;124m"[39m[38;5;124mLog GDP Per Capita[39m[38;5;124m"[39m],
[0;32m   (...)[0m
[1;32m     36[0m     )
[1;32m     37[0m )

File [0;32m~/anaconda3/envs/infovis/lib/python3.11/site-packages/pandas/core/frame.py:3761[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   3759[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mnlevels [38;5;241m>[39m [38;5;241m1[39m:
[1;32m   3760[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getitem_multilevel(key)
[0;32m-> 3761[0m indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mcolumns[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mkey[49m[43m)[49m
[1;32m   3762[0m [38;5;28;01mif[39;00m is_integer(indexer):
[1;32m   3763[0m     indexer [38;5;241m=[39m [indexer]

File [0;32m~/anaconda3/envs/infovis/lib/python3.11/site-packages/pandas/core/indexes/base.py:3654[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3652[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_engine[38;5;241m.[39mget_loc(casted_key)
[1;32m   3653[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m-> 3654[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3655[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3656[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3657[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3658[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3659[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'Bipolar disorder (%)'

